Refactor address to nusnetID
AY2021S1-CS2103-F09-1/tp pull request #27
Opened 2020-09-21 14:38 UTC by theodoreleebrant

TAskmaster does not need address, unlike address book. However, it needs
a unique identifier for a student, which is the nusnet ID.

The address field of the addressbook is therefore changed to nusnetID.
The validation of the nusnet ID is changed from the address validation.

Fixes #18

2020-09-21 16:26 UTC, jayarengam requested changes
Looks good apart from:
- naming of 'NusnetID' class
- one test file needs to be updated
- some fields still have the 'address' name

2020-09-21 16:26 UTC, jayarengam commented on src/test/java/seedu/address/model/person/NusnetIDTest.java
> +    public void constructor_invalidAddress_throwsIllegalArgumentException() {
Consider replacing address with NusnetId

2020-09-21 16:26 UTC, jayarengam commented on src/test/java/seedu/address/testutil/PersonBuilder.java
> +    public static final String DEFAULT_ADDRESS = "e0000000";
rename field

2020-09-21 16:26 UTC, jayarengam commented on src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
>      public EditPersonDescriptorBuilder withAddress(String address) {
rename field

2020-09-21 16:26 UTC, jayarengam commented on src/test/java/seedu/address/model/person/NusnetIDTest.java
> +        assertTrue(NusnetID.isValidAddress("Leng Inc; 1234 Market St; San Francisco CA 2349879; USA")); // long address
Please update testcases

2020-09-21 16:26 UTC, jayarengam commented on src/test/java/seedu/address/model/person/NusnetIDTest.java
> +public class NusnetIDTest {
Please consider changing name to NusnetIdTest

2020-09-21 16:26 UTC, jayarengam commented on src/test/java/seedu/address/logic/parser/ParserUtilTest.java
> +    private static final String INVALID_ADDRESS = "e1123456";
Consider renaming field

2020-09-21 16:26 UTC, jayarengam commented on src/main/java/seedu/address/model/person/NusnetID.java
> +public class NusnetID {
Consider renaming class to NusnetId (coding standard)

2020-09-23 10:09 UTC, theodoreleebrant commented
Updated according to coding standard and checkstyle. Updated testcases.

2020-09-25 06:25 UTC, jayarengam reviewed
LGTM, thanks for making the changes

2020-09-25 06:25 UTC, jayarengam approved these changes

2020-09-25 06:26 UTC, merged